# fly.toml app configuration file for Fly.io

app = 'bazodiac'
primary_region = 'fra'

[build]

[env]
  PORT = "8787"
  NODE_ENV = "production"
  BAZI_ENGINE_URL = "https://baziengine-v2.fly.dev"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 4

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"
